language: cpp

before_install:
  - sudo add-apt-repository --yes ppa:apokluda/boost1.53
  - sudo apt-get --yes update
  - sudo apt-get --yes install libboost1.53-all-dev

script:
  - make -C Build config=release
